### ISSUE TITLE
Firefox fails to create

### ISSUE THREAD

**Issue by iinuwa** [GramThanos/WebDevAuthn#2]
Firefox throws an error when using creating a credential with `direct` attestation specified.

Seems to be bailing on the date format [here](https://github.com/GramThanos/WebDevAuthn/blob/7339c46a57069cb544200c4f1d8d5412f8917ee9/js/webauthn-authenticator.js#L1318-L1319).

**Comment by GramThanos** [comment]
Fixed on 83ee6b9bc9c66b44b15ad2f927ee211bfcfc0eaf
Thanks!
