### ISSUE TITLE
Support for Transmitting Custom Data from Authenticator Devices to RP

### ISSUE THREAD

**Issue by derekcmini** [GramThanos/WebDevAuthn#7]
Can authenticator devices transmit custom data (e.g., data that is not covered by the specification) to the RP, and if so, how can this be done? Can the virtual authenticators in your project provide this functionality?

**Comment by GramThanos** [comment]
You can do that that by editing the `create` and `get` functions of the virtual authenticator code:
https://github.com/GramThanos/WebDevAuthn/blob/main/js/webauthn-authenticator.js#L414
https://github.com/GramThanos/WebDevAuthn/blob/main/js/webauthn-authenticator.js#L600

**Comment by derekcmini** [comment]
Thank you for your guidance. I will refer to your instructions and proceed with the testing modifications.
